---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: busybox
  template:
    metadata:
      labels:
        appname: busybox
    spec:
      containers:
      - image: quay.io/nirsof/busybox:stable
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ['sh', '-c', 'trap exit TERM; while true; do echo $(date) | tee -a /mnt/test/outfile; sync; sleep 10 & wait; done']
        volumeMounts:
          - name: mypvc
            mountPath: /mnt/test
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: busybox-pvc
