---
resources:
  - ../../base
namespace: vm-pvc
labels:
  - pairs:
      app: vm-pvc
patches:
  - target:
      kind: Subscription
      name: subscription
    patch: |-
      - op: replace
        path: /metadata/annotations/apps.open-cluster-management.io~1github-path
        value: workloads/kubevirt/vm-pvc/k8s-regional
