---
resources:
  - ../../base
commonLabels:
  app: vm-pvc-k8s
patches:
  - target:
      kind: ApplicationSet
      name: APPSET_NAME
    patch: |-
      # ApplicationSet name
      - op: replace
        path: /metadata/name
        value: vm-pvc-k8s-appset
      # ConfigMap reference
      - op: replace
        path: /spec/generators/0/clusterDecisionResource/configMapRef
        value: vm-pvc-k8s-appset
      # Placement label selector
      - op: replace
        path: /spec/generators/0/clusterDecisionResource/labelSelector/matchLabels/cluster.open-cluster-management.io~1placement
        value: vm-pvc-k8s-appset
      # Workload path
      - op: replace
        path: /spec/template/spec/source/path
        value: workloads/kubevirt/vm-pvc/k8s-regional
      # Target namespace
      - op: replace
        path: /spec/template/spec/destination/namespace
        value: vm-pvc-k8s
      # Application name template
      - op: replace
        path: /spec/template/metadata/name
        value: vm-pvc-k8s-appset-{{name}}
  - target:
      kind: Placement
      name: APPSET_NAME
    patch: |-
      # Placement name
      - op: replace
        path: /metadata/name
        value: vm-pvc-k8s-appset
      # Placement label
      - op: replace
        path: /metadata/labels/cluster.open-cluster-management.io~1placement
        value: vm-pvc-k8s-appset
  - target:
      kind: ConfigMap
      name: APPSET_NAME
    patch: |-
      # ConfigMap name
      - op: replace
        path: /metadata/name
        value: vm-pvc-k8s-appset
      # ConfigMap label
      - op: replace
        path: /metadata/labels/cluster.open-cluster-management.io~1placement
        value: vm-pvc-k8s-appset
